############# Carrier board IO ###################
set_property PACKAGE_PIN AL31		[get_ports nCOLDRST	]
set_property PACKAGE_PIN AL36		[get_ports nBPI_FLASH_CS]
set_property PACKAGE_PIN BA37 		[get_ports {LA[2]}	]
set_property PACKAGE_PIN BB37 		[get_ports {LA[3]}	]
set_property PACKAGE_PIN AW38 		[get_ports {LA[4]}	]
set_property PACKAGE_PIN AY38 		[get_ports {LA[5]}	]
set_property PACKAGE_PIN BB38 		[get_ports {LA[6]}	]
set_property PACKAGE_PIN BB39 		[get_ports {LA[7]}	]
set_property PACKAGE_PIN BA39 		[get_ports {LA[8]}	]
set_property PACKAGE_PIN BA40 		[get_ports {LA[9]}	]
set_property PACKAGE_PIN AT41 		[get_ports {LA[10]}	]
set_property PACKAGE_PIN AU42 		[get_ports {LA[11]}	]
set_property PACKAGE_PIN BA42 		[get_ports {LA[12]}	]
set_property PACKAGE_PIN AU41 		[get_ports {LA[13]}	]
set_property PACKAGE_PIN AV41 		[get_ports {LA[14]}	]
set_property PACKAGE_PIN AM32		[get_ports {LA[15]}	]
set_property PACKAGE_PIN AM33		[get_ports {LA[16]}	]
set_property PACKAGE_PIN AN33		[get_ports {LA[17]}	]
set_property PACKAGE_PIN AL29		[get_ports {LA[18]}	]
set_property PACKAGE_PIN AL30		[get_ports {LA[19]}	]
set_property PACKAGE_PIN AH29		[get_ports {LA[20]}	]
set_property PACKAGE_PIN AH30		[get_ports {LA[21]}	]
set_property PACKAGE_PIN AJ30		[get_ports {LA[22]}	]
set_property PACKAGE_PIN AK30		[get_ports {LA[23]}	]
set_property PACKAGE_PIN AG29		[get_ports {LA[24]}	]
set_property PACKAGE_PIN AK28		[get_ports {LA[25]}	]
set_property PACKAGE_PIN AK29		[get_ports {LA[26]}	]
set_property PACKAGE_PIN AF30		[get_ports {LA[27]}	]
set_property PACKAGE_PIN AG31		[get_ports {LA[28]}	]
set_property PACKAGE_PIN AH28		[get_ports {LA[29]}	]
set_property PACKAGE_PIN AJ28		[get_ports {LA[30]}	]
	
set_property PACKAGE_PIN AJ35		[get_ports {LAD[0]}	]
set_property PACKAGE_PIN AH34		[get_ports {LAD[1]}	]
set_property PACKAGE_PIN AJ31		[get_ports {LAD[2]}	]
set_property PACKAGE_PIN AL35		[get_ports {LAD[3]}	]
set_property PACKAGE_PIN AK35		[get_ports {LAD[4]}	]
set_property PACKAGE_PIN AH33		[get_ports {LAD[5]}	]
set_property PACKAGE_PIN AG33		[get_ports {LAD[6]}	]
set_property PACKAGE_PIN AM37		[get_ports {LAD[7]}	]
set_property PACKAGE_PIN AP35		[get_ports {LAD[8]}	]
set_property PACKAGE_PIN AN35		[get_ports {LAD[9]}	]
set_property PACKAGE_PIN AL37		[get_ports {LAD[10]}	]
set_property PACKAGE_PIN AK37		[get_ports {LAD[11]}	]
set_property PACKAGE_PIN AJ37		[get_ports {LAD[12]}	]
set_property PACKAGE_PIN AJ36		[get_ports {LAD[13]}	]
set_property PACKAGE_PIN AN36		[get_ports {LAD[14]}	]
set_property PACKAGE_PIN AM36		[get_ports {LAD[15]}	]
set_property PACKAGE_PIN BA41 		[get_ports nLOE		]
set_property PACKAGE_PIN BB41 		[get_ports {nLWE[0]}	]
set_property PACKAGE_PIN AG32		[get_ports {nLWE[1]}	]
	
set_property PACKAGE_PIN AN41 		[get_ports FPGA_UART_SIN	]
set_property PACKAGE_PIN AR37 		[get_ports FPGA_UART_SOUT	]
	
set_property PACKAGE_PIN AK8 		[get_ports CLK156_25MHZ3_P	]
set_property PACKAGE_PIN AK7 		[get_ports CLK156_25MHZ3_N	]
	
# P2040 PCIe	
set_property PACKAGE_PIN W2  		[get_ports SD_RX04_P	]
set_property PACKAGE_PIN W1  		[get_ports SD_RX04_N	]
set_property PACKAGE_PIN Y4  		[get_ports SD_TX04_P	]
set_property PACKAGE_PIN Y3  		[get_ports SD_TX04_N	]
set_property PACKAGE_PIN AA2 		[get_ports SD_RX05_P	]
set_property PACKAGE_PIN AA1 		[get_ports SD_RX05_N	]
set_property PACKAGE_PIN AA6 		[get_ports SD_TX05_P	]
set_property PACKAGE_PIN AA5 		[get_ports SD_TX05_N	]
set_property PACKAGE_PIN Y8  		[get_ports CLK100MHZ0_P	]
set_property PACKAGE_PIN Y7  		[get_ports CLK100MHZ0_N	]
	
# Backplane PCIe	
set_property PACKAGE_PIN AR2  		[get_ports AMC_TX4_P	]
set_property PACKAGE_PIN AR1  		[get_ports AMC_TX4_N	]
set_property PACKAGE_PIN AP8  		[get_ports AMC_RX4_P	]
set_property PACKAGE_PIN AP7  		[get_ports AMC_RX4_N	]
set_property PACKAGE_PIN AT4  		[get_ports AMC_TX5_P	]
set_property PACKAGE_PIN AT3  		[get_ports AMC_TX5_N	]
set_property PACKAGE_PIN AR6  		[get_ports AMC_RX5_P	]
set_property PACKAGE_PIN AR5  		[get_ports AMC_RX5_N	]
set_property PACKAGE_PIN AU2  		[get_ports AMC_TX6_P	]
set_property PACKAGE_PIN AU1  		[get_ports AMC_TX6_N	]
set_property PACKAGE_PIN AU6  		[get_ports AMC_RX6_P	]
set_property PACKAGE_PIN AU5  		[get_ports AMC_RX6_N	]
set_property PACKAGE_PIN AV4  		[get_ports AMC_TX7_P	]
set_property PACKAGE_PIN AV3  		[get_ports AMC_TX7_N	]
set_property PACKAGE_PIN AV8  		[get_ports AMC_RX7_P	]
set_property PACKAGE_PIN AV7  		[get_ports AMC_RX7_N	]
set_property PACKAGE_PIN AW2  		[get_ports AMC_TX8_P	]
set_property PACKAGE_PIN AW1  		[get_ports AMC_TX8_N	]
set_property PACKAGE_PIN AW6  		[get_ports AMC_RX8_P	]
set_property PACKAGE_PIN AW5  		[get_ports AMC_RX8_N	]
set_property PACKAGE_PIN AY4  		[get_ports AMC_TX9_P	]
set_property PACKAGE_PIN AY3  		[get_ports AMC_TX9_N	]
set_property PACKAGE_PIN AY8  		[get_ports AMC_RX9_P	]
set_property PACKAGE_PIN AY7  		[get_ports AMC_RX9_N	]
set_property PACKAGE_PIN BA2  		[get_ports AMC_TX10_P	]
set_property PACKAGE_PIN BA1  		[get_ports AMC_TX10_N	]
set_property PACKAGE_PIN BA6  		[get_ports AMC_RX10_P	]
set_property PACKAGE_PIN BA5  		[get_ports AMC_RX10_N	]
set_property PACKAGE_PIN BB4  		[get_ports AMC_TX11_P	]
set_property PACKAGE_PIN BB3  		[get_ports AMC_TX11_N	]
set_property PACKAGE_PIN BB8  		[get_ports AMC_RX11_P	]
set_property PACKAGE_PIN BB7  		[get_ports AMC_RX11_N	]
set_property PACKAGE_PIN AT8  		[get_ports CLK100MHZ1_P	]
set_property PACKAGE_PIN AT7  		[get_ports CLK100MHZ1_N	]
set_property PACKAGE_PIN AU10 		[get_ports FCLKA_P	]
set_property PACKAGE_PIN AU9  		[get_ports FCLKA_N	]

## =================== FMC IO =========================
## ------ FMC LA
# set_property PACKAGE_PIN C25 		[get_ports {FMC_LA_P0}	]
# set_property PACKAGE_PIN C26 		[get_ports {FMC_LA_N0}	]
set_property PACKAGE_PIN D27 		[get_ports {FMC_LA_P1}	]
set_property PACKAGE_PIN D28 		[get_ports {FMC_LA_N1}	]
set_property PACKAGE_PIN A24 		[get_ports {FMC_LA_P2}	]
set_property PACKAGE_PIN A25 		[get_ports {FMC_LA_N2}	]
set_property PACKAGE_PIN B22 		[get_ports {FMC_LA_P3}	]
set_property PACKAGE_PIN A22 		[get_ports {FMC_LA_N3}	]
set_property PACKAGE_PIN A26 		[get_ports {FMC_LA_P4}	]
set_property PACKAGE_PIN A27 		[get_ports {FMC_LA_N4}	]
set_property PACKAGE_PIN C23 		[get_ports {FMC_LA_P5}	]
set_property PACKAGE_PIN B23 		[get_ports {FMC_LA_N5}	]
set_property PACKAGE_PIN B26 		[get_ports {FMC_LA_P6}	]
set_property PACKAGE_PIN B27 		[get_ports {FMC_LA_N6}	]
set_property PACKAGE_PIN E23 		[get_ports {FMC_LA_P7}	]
set_property PACKAGE_PIN E24 		[get_ports {FMC_LA_N7}	]
set_property PACKAGE_PIN F22 		[get_ports {FMC_LA_P8}	]
# set_property PACKAGE_PIN E22 		[get_ports {FMC_LA_N8}	]
set_property PACKAGE_PIN F25 		[get_ports {FMC_LA_P9}	]
set_property PACKAGE_PIN E25 		[get_ports {FMC_LA_N9}	]
set_property PACKAGE_PIN D22 		[get_ports {FMC_LA_P10}	]
set_property PACKAGE_PIN D23 		[get_ports {FMC_LA_N10}	]
set_property PACKAGE_PIN B28 		[get_ports {FMC_LA_P11}	]
set_property PACKAGE_PIN B29 		[get_ports {FMC_LA_N11}	]
set_property PACKAGE_PIN A31 		[get_ports {FMC_LA_P12}	]
set_property PACKAGE_PIN A32 		[get_ports {FMC_LA_N12}	]
set_property PACKAGE_PIN A29 		[get_ports {FMC_LA_P13}	]
set_property PACKAGE_PIN A30 		[get_ports {FMC_LA_N13}	]
set_property PACKAGE_PIN C31 		[get_ports {FMC_LA_P14}	]
set_property PACKAGE_PIN B31 		[get_ports {FMC_LA_N14}	]
set_property PACKAGE_PIN D30 		[get_ports {FMC_LA_P15}	]
set_property PACKAGE_PIN C30 		[get_ports {FMC_LA_N15}	]
set_property PACKAGE_PIN E27 		[get_ports {FMC_LA_P16}	]
set_property PACKAGE_PIN E28 		[get_ports {FMC_LA_N16}	]
	
# set_property PACKAGE_PIN J25 		[get_ports {FMC_LA_P17}	]
# set_property PACKAGE_PIN J26 		[get_ports {FMC_LA_N17}	]
set_property PACKAGE_PIN M24 		[get_ports {FMC_LA_P18}	]
set_property PACKAGE_PIN L24 		[get_ports {FMC_LA_N18}	]
set_property PACKAGE_PIN G21 		[get_ports {FMC_LA_P19}	]
set_property PACKAGE_PIN G22 		[get_ports {FMC_LA_N19}	]
set_property PACKAGE_PIN G26 		[get_ports {FMC_LA_P20}	]
set_property PACKAGE_PIN G27 		[get_ports {FMC_LA_N20}	]
set_property PACKAGE_PIN G28 		[get_ports {FMC_LA_P21}	]
set_property PACKAGE_PIN G29 		[get_ports {FMC_LA_N21}	]
# set_property PACKAGE_PIN K28 		[get_ports {FMC_LA_P22}	]
# set_property PACKAGE_PIN J28 		[get_ports {FMC_LA_N22}	]
set_property PACKAGE_PIN H28 		[get_ports {FMC_LA_P23}	]
set_property PACKAGE_PIN H29 		[get_ports {FMC_LA_N23}	]
set_property PACKAGE_PIN K27 		[get_ports {FMC_LA_P24}	]
set_property PACKAGE_PIN J27 		[get_ports {FMC_LA_N24}	]
set_property PACKAGE_PIN M22 		[get_ports {FMC_LA_P25}	]
set_property PACKAGE_PIN L22 		[get_ports {FMC_LA_N25}	]
# set_property PACKAGE_PIN L25 		[get_ports {FMC_LA_P26}	]
# set_property PACKAGE_PIN L26 		[get_ports {FMC_LA_N26}	]
# set_property PACKAGE_PIN K22 		[get_ports {FMC_LA_P27}	]
# set_property PACKAGE_PIN J22 		[get_ports {FMC_LA_N27}	]
# set_property PACKAGE_PIN M21 		[get_ports {FMC_LA_P28}	]
# set_property PACKAGE_PIN L21 		[get_ports {FMC_LA_N28}	]
# set_property PACKAGE_PIN P25 		[get_ports {FMC_LA_P29}	]
# set_property PACKAGE_PIN P26 		[get_ports {FMC_LA_N29}	]
# set_property PACKAGE_PIN P22 		[get_ports {FMC_LA_P30}	]
# set_property PACKAGE_PIN P23 		[get_ports {FMC_LA_N30}	]
# set_property PACKAGE_PIN N25 		[get_ports {FMC_LA_P31}	]
# set_property PACKAGE_PIN N26 		[get_ports {FMC_LA_N31}	]
# set_property PACKAGE_PIN N23 		[get_ports {FMC_LA_P32}	]
# set_property PACKAGE_PIN N24 		[get_ports {FMC_LA_N32}	]
# set_property PACKAGE_PIN M27 		[get_ports {FMC_LA_P33}	]
# set_property PACKAGE_PIN L27 		[get_ports {FMC_LA_N33}	]
	
## ------ FMC HA	
# set_property PACKAGE_PIN E19 		[get_ports {FMC_HA_P0}	]
# set_property PACKAGE_PIN E18 		[get_ports {FMC_HA_N0}	]
# set_property PACKAGE_PIN G19 		[get_ports {FMC_HA_P1}	]
# set_property PACKAGE_PIN F19 		[get_ports {FMC_HA_N1}	]
# set_property PACKAGE_PIN C19 		[get_ports {FMC_HA_P2}	]
# set_property PACKAGE_PIN B19 		[get_ports {FMC_HA_N2}	]
# set_property PACKAGE_PIN A16 		[get_ports {FMC_HA_P3}	]
# set_property PACKAGE_PIN A15 		[get_ports {FMC_HA_N3}	]
# set_property PACKAGE_PIN A20 		[get_ports {FMC_HA_P4}	]
# set_property PACKAGE_PIN A19 		[get_ports {FMC_HA_N4}	]
# set_property PACKAGE_PIN B17 		[get_ports {FMC_HA_P5}	]
# set_property PACKAGE_PIN A17 		[get_ports {FMC_HA_N5}	]
# set_property PACKAGE_PIN B21 		[get_ports {FMC_HA_P6}	]
# set_property PACKAGE_PIN A21 		[get_ports {FMC_HA_N6}	]
# set_property PACKAGE_PIN D20 		[get_ports {FMC_HA_P7}	]
# set_property PACKAGE_PIN C20 		[get_ports {FMC_HA_N7}	]
# set_property PACKAGE_PIN F17 		[get_ports {FMC_HA_P8}	]
# set_property PACKAGE_PIN E17 		[get_ports {FMC_HA_N8}	]
# set_property PACKAGE_PIN D21 		[get_ports {FMC_HA_P9}	]
# set_property PACKAGE_PIN C21 		[get_ports {FMC_HA_N9}	]
# set_property PACKAGE_PIN D18 		[get_ports {FMC_HA_P10}	]
# set_property PACKAGE_PIN D17 		[get_ports {FMC_HA_N10}	]
# set_property PACKAGE_PIN F20 		[get_ports {FMC_HA_P11}	]
# set_property PACKAGE_PIN E20 		[get_ports {FMC_HA_N11}	]
# set_property PACKAGE_PIN K17 		[get_ports {FMC_HA_P12}	]
# set_property PACKAGE_PIN J17 		[get_ports {FMC_HA_N12}	]
# set_property PACKAGE_PIN J20 		[get_ports {FMC_HA_P13}	]
# set_property PACKAGE_PIN H20 		[get_ports {FMC_HA_N13}	]
# set_property PACKAGE_PIN H18 		[get_ports {FMC_HA_P14}	]
# set_property PACKAGE_PIN G17 		[get_ports {FMC_HA_N14}	]
# set_property PACKAGE_PIN M17 		[get_ports {FMC_HA_P15}	]
# set_property PACKAGE_PIN L17 		[get_ports {FMC_HA_N15}	]
# set_property PACKAGE_PIN N19 		[get_ports {FMC_HA_P16}	]
# set_property PACKAGE_PIN N18 		[get_ports {FMC_HA_N16}	]
# set_property PACKAGE_PIN G14 		[get_ports {FMC_HA_P17}	]
# set_property PACKAGE_PIN G13 		[get_ports {FMC_HA_N17}	]
# set_property PACKAGE_PIN H15 		[get_ports {FMC_HA_P18}	]
# set_property PACKAGE_PIN H14 		[get_ports {FMC_HA_N18}	]
# set_property PACKAGE_PIN J13 		[get_ports {FMC_HA_P19}	]
# set_property PACKAGE_PIN H13 		[get_ports {FMC_HA_N19}	]
# set_property PACKAGE_PIN K12 		[get_ports {FMC_HA_P20}	]
# set_property PACKAGE_PIN J12 		[get_ports {FMC_HA_N20}	]
# set_property PACKAGE_PIN K15 		[get_ports {FMC_HA_P21}	]
# set_property PACKAGE_PIN J15 		[get_ports {FMC_HA_N21}	]
# set_property PACKAGE_PIN K14 		[get_ports {FMC_HA_P22}	]
# set_property PACKAGE_PIN K13 		[get_ports {FMC_HA_N22}	]
# set_property PACKAGE_PIN L16 		[get_ports {FMC_HA_P23}	]
# set_property PACKAGE_PIN L15 		[get_ports {FMC_HA_N23}	]
	
	
## ------ FMC HB	
# set_property PACKAGE_PIN K39 		[get_ports {FMC_HB_P0}	]
# set_property PACKAGE_PIN K40 		[get_ports {FMC_HB_N0}	]
# set_property PACKAGE_PIN E40 		[get_ports {FMC_HB_P1}	]
# set_property PACKAGE_PIN D40 		[get_ports {FMC_HB_N1}	]
# set_property PACKAGE_PIN A40 		[get_ports {FMC_HB_P2}	]
# set_property PACKAGE_PIN A41 		[get_ports {FMC_HB_N2}	]
# set_property PACKAGE_PIN D41 		[get_ports {FMC_HB_P3}	]
# set_property PACKAGE_PIN D42 		[get_ports {FMC_HB_N3}	]
# set_property PACKAGE_PIN B41 		[get_ports {FMC_HB_P4}	]
# set_property PACKAGE_PIN B42 		[get_ports {FMC_HB_N4}	]
# set_property PACKAGE_PIN F42 		[get_ports {FMC_HB_P5}	]
# set_property PACKAGE_PIN E42 		[get_ports {FMC_HB_N5}	]
# set_property PACKAGE_PIN L39 		[get_ports {FMC_HB_P6}	]
# set_property PACKAGE_PIN L40 		[get_ports {FMC_HB_N6}	]
# set_property PACKAGE_PIN H40 		[get_ports {FMC_HB_P7}	]
# set_property PACKAGE_PIN H41 		[get_ports {FMC_HB_N7}	]
# set_property PACKAGE_PIN H39 		[get_ports {FMC_HB_P8}	]
# set_property PACKAGE_PIN G39 		[get_ports {FMC_HB_N8}	]
# set_property PACKAGE_PIN G41 		[get_ports {FMC_HB_P9}	]
# set_property PACKAGE_PIN G42 		[get_ports {FMC_HB_N9}	]
# set_property PACKAGE_PIN F40 		[get_ports {FMC_HB_P10}	]
# set_property PACKAGE_PIN F41 		[get_ports {FMC_HB_N10}	]
# set_property PACKAGE_PIN J40 		[get_ports {FMC_HB_P11}	]
# set_property PACKAGE_PIN J41 		[get_ports {FMC_HB_N11}	]
# set_property PACKAGE_PIN K42 		[get_ports {FMC_HB_P12}	]
# set_property PACKAGE_PIN J42 		[get_ports {FMC_HB_N12}	]
# set_property PACKAGE_PIN M42 		[get_ports {FMC_HB_P13}	]
# set_property PACKAGE_PIN L42 		[get_ports {FMC_HB_N13}	]
# set_property PACKAGE_PIN K37 		[get_ports {FMC_HB_P14}	]
# set_property PACKAGE_PIN K38 		[get_ports {FMC_HB_N14}	]
# set_property PACKAGE_PIN M36 		[get_ports {FMC_HB_P15}	]
# set_property PACKAGE_PIN L37 		[get_ports {FMC_HB_N15}	]
# set_property PACKAGE_PIN M37 		[get_ports {FMC_HB_P16}	]
# set_property PACKAGE_PIN M38 		[get_ports {FMC_HB_N16}	]
# set_property PACKAGE_PIN M41 		[get_ports {FMC_HB_P17}	]
# set_property PACKAGE_PIN L41 		[get_ports {FMC_HB_N17}	]
# set_property PACKAGE_PIN R42 		[get_ports {FMC_HB_P18}	]
# set_property PACKAGE_PIN P42 		[get_ports {FMC_HB_N18}	]
# set_property PACKAGE_PIN N38 		[get_ports {FMC_HB_P19}	]
# set_property PACKAGE_PIN M39 		[get_ports {FMC_HB_N19}	]
# set_property PACKAGE_PIN R40 		[get_ports {FMC_HB_P20}	]
# set_property PACKAGE_PIN P40 		[get_ports {FMC_HB_N20}	]
# set_property PACKAGE_PIN N39 		[get_ports {FMC_HB_P21}	]
# set_property PACKAGE_PIN N40 		[get_ports {FMC_HB_N21}	]
	
# -- FMC SERDES	
set_property PACKAGE_PIN J6 		[get_ports FMC_RX7_P	]
set_property PACKAGE_PIN J5 		[get_ports FMC_RX7_N	]
set_property PACKAGE_PIN L6 		[get_ports FMC_RX6_P	]
set_property PACKAGE_PIN L5 		[get_ports FMC_RX6_N	]
set_property PACKAGE_PIN N6 		[get_ports FMC_RX5_P	]
set_property PACKAGE_PIN N5 		[get_ports FMC_RX5_N	]
set_property PACKAGE_PIN P8 		[get_ports FMC_RX4_P	]
set_property PACKAGE_PIN P7 		[get_ports FMC_RX4_N	]
	
# set_property PACKAGE_PIN K4 		[get_ports FMC_TX7_P	]
# set_property PACKAGE_PIN K3 		[get_ports FMC_TX7_N	]
# set_property PACKAGE_PIN L2 		[get_ports FMC_TX6_P	]
# set_property PACKAGE_PIN L1 		[get_ports FMC_TX6_N	]
# set_property PACKAGE_PIN M4 		[get_ports FMC_TX5_P	]
# set_property PACKAGE_PIN M3 		[get_ports FMC_TX5_N	]
# set_property PACKAGE_PIN N2 		[get_ports FMC_TX4_P	]
# set_property PACKAGE_PIN N1 		[get_ports FMC_TX4_N	]
	
#set_property PACKAGE_PIN K8 		[get_ports CLK156_25MHZ1_P	]
#set_property PACKAGE_PIN K7 		[get_ports CLK156_25MHZ1_N	]
#set_property PACKAGE_PIN M8 		[get_ports CLK125MHZ7_P	]
#set_property PACKAGE_PIN M7 		[get_ports CLK125MHZ7_N	]


set_property PACKAGE_PIN E6  		[get_ports FMC_RX3_P	]
set_property PACKAGE_PIN E5  		[get_ports FMC_RX3_N	]
set_property PACKAGE_PIN F8  		[get_ports FMC_RX2_P	]
set_property PACKAGE_PIN F7  		[get_ports FMC_RX2_N	]
set_property PACKAGE_PIN G6  		[get_ports FMC_RX1_P	]
set_property PACKAGE_PIN G5  		[get_ports FMC_RX1_N	]
set_property PACKAGE_PIN H8  		[get_ports FMC_RX0_P	]
set_property PACKAGE_PIN H7  		[get_ports FMC_RX0_N	]
			
# set_property PACKAGE_PIN F4  		[get_ports FMC_TX3_P	]
# set_property PACKAGE_PIN F3  		[get_ports FMC_TX3_N	]
# set_property PACKAGE_PIN G2  		[get_ports FMC_TX2_P	]
# set_property PACKAGE_PIN G1  		[get_ports FMC_TX2_N	]
# set_property PACKAGE_PIN H4  		[get_ports FMC_TX1_P	]
# set_property PACKAGE_PIN H3  		[get_ports FMC_TX1_N	]
# set_property PACKAGE_PIN J2  		[get_ports FMC_TX0_P	]
# set_property PACKAGE_PIN J1  		[get_ports FMC_TX0_N	]
	
set_property PACKAGE_PIN E10 		[get_ports FMC_GBTCLK0_P]
set_property PACKAGE_PIN E9  		[get_ports FMC_GBTCLK0_N]
# set_property PACKAGE_PIN G10 		[get_ports FMC_GBTCLK1_P]
# set_property PACKAGE_PIN G9  		[get_ports FMC_GBTCLK1_N]


# ======== Carrier IOSTANDARD ========

set_property IOSTANDARD LVCMOS18 	[get_ports {FPGA_UART_SIN}]
set_property IOSTANDARD LVCMOS18 	[get_ports {FPGA_UART_SOUT}]

set_property IOSTANDARD LVCMOS18 	[get_ports {LA[30]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[29]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[28]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[27]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[26]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[25]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[24]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[23]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[22]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[21]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[20]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[19]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[18]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[17]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[16]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[15]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[14]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[13]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[12]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[11]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[10]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[9]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[8]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[7]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[6]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[5]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[4]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[3]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LA[2]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[15]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[14]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[13]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[12]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[11]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[10]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[9]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[8]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[7]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[6]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[5]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[4]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[3]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[2]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[1]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {LAD[0]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {nLWE[1]}]
set_property IOSTANDARD LVCMOS18 	[get_ports {nLWE[0]}]
set_property IOSTANDARD LVCMOS18 	[get_ports nBPI_FLASH_CS]
set_property IOSTANDARD LVCMOS18 	[get_ports nCOLDRST]
set_property IOSTANDARD LVCMOS18 	[get_ports nLOE]

# ======== FMC IOSTANDARD ========
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P0}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N0}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P1}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N1}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P2}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N2}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P3}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N3}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P4}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N4}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P5}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N5}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P6}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N6}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P7}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N7}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P8}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N8}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P9}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N9}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P10}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N10}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P11}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N11}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P12}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N12}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P13}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N13}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P14}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N14}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P15}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N15}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P16}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N16}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P17}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N17}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P18}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N18}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P19}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N19}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P20}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N20}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P21}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N21}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P22}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N22}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P23}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N23}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P24}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N24}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P25}	]
set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N25}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P26}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N26}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P27}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N27}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P28}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N28}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P29}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N29}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P30}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N30}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P31}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N31}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P32}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N32}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_P33}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_LA_N33}	]

## ------ FMC HA
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P0}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N0}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P1}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N1}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P2}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N2}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P3}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N3}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P4}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N4}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P5}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N5}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P6}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N6}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P7}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N7}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P8}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N8}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P9}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N9}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P10}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N10}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P11}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N11}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P12}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N12}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P13}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N13}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P14}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N14}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P15}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N15}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P16}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N16}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P17}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N17}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P18}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N18}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P19}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N19}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P20}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N20}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P21}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N21}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P22}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N22}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_P23}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HA_N23}	]

## ------ FMC HB
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P0}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N0}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P1}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N1}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P2}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N2}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P3}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N3}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P4}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N4}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P5}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N5}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P6}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N6}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P7}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N7}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P8}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N8}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P9}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N9}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P10}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N10}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P11}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N11}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P12}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N12}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P13}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N13}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P14}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N14}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P15}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N15}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P16}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N16}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P17}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N17}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P18}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N18}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P19}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N19}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P20}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N20}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_P21}	]
# set_property IOSTANDARD LVCMOS18	[get_ports {FMC_HB_N21}	]


# ======== Bitstream settings ========
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]

