# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k420tffg1156-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.cache/wt [current_project]
set_property parent.project_path /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_ip -quiet /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/decoder_10b8b_rom/decoder_10b8b_rom.xci
set_property is_locked true [get_files /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/decoder_10b8b_rom/decoder_10b8b_rom.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top decoder_10b8b_rom -part xc7k420tffg1156-2 -mode out_of_context

rename_ref -prefix_all decoder_10b8b_rom_

write_checkpoint -force -noxdef decoder_10b8b_rom.dcp

catch { report_utilization -file decoder_10b8b_rom_utilization_synth.rpt -pb decoder_10b8b_rom_utilization_synth.pb }

if { [catch {
  file copy -force /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/decoder_10b8b_rom_synth_1/decoder_10b8b_rom.dcp /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/decoder_10b8b_rom/decoder_10b8b_rom.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/decoder_10b8b_rom/decoder_10b8b_rom_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/decoder_10b8b_rom/decoder_10b8b_rom_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/decoder_10b8b_rom/decoder_10b8b_rom_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/decoder_10b8b_rom/decoder_10b8b_rom_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.ip_user_files/ip/decoder_10b8b_rom]} {
  catch { 
    file copy -force /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/decoder_10b8b_rom/decoder_10b8b_rom_stub.v /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.ip_user_files/ip/decoder_10b8b_rom
  }
}

if {[file isdir /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.ip_user_files/ip/decoder_10b8b_rom]} {
  catch { 
    file copy -force /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/decoder_10b8b_rom/decoder_10b8b_rom_stub.vhdl /root/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.ip_user_files/ip/decoder_10b8b_rom
  }
}
