# set_property PACKAGE_PIN J29	[get_ports {USER[6]}	]
# set_property PACKAGE_PIN H23	[get_ports {USER[4]}	]
# set_property PACKAGE_PIN B25	[get_ports AMC_TX3SEL_P	]
# set_property PACKAGE_PIN A26	[get_ports AMC_TX3SEL_N	]
# set_property PACKAGE_PIN F25	[get_ports FPCLKA_P	]
# set_property PACKAGE_PIN F26	[get_ports FPCLKA_N	]
# set_property PACKAGE_PIN G25	[get_ports FPCLKB_P]
# set_property PACKAGE_PIN G26	[get_ports FPCLKB_N]
# set_property PACKAGE_PIN M25	[get_ports {USER[5]}]
# set_property PACKAGE_PIN G16	[get_ports {USER[0]}]
# set_property PACKAGE_PIN H19	[get_ports nLVDS_CBS_RST]
# set_property PACKAGE_PIN H20	[get_ports nPLL_RST]
# set_property PACKAGE_PIN F18	[get_ports {USER[1]}]
# set_property PACKAGE_PIN D20	[get_ports FPCLKC_P]
# set_property PACKAGE_PIN D21	[get_ports FPCLKC_N]
# set_property PACKAGE_PIN C18	[get_ports FPCLKD_P]
# set_property PACKAGE_PIN C19	[get_ports FPCLKD_N]
# set_property PACKAGE_PIN D22	[get_ports {USER[2]}]
# set_property PACKAGE_PIN H22	[get_ports {USER[3]}]
# set_property PACKAGE_PIN AG15	[get_ports SDA_LLLX]
# set_property PACKAGE_PIN AD25	[get_ports nTHERM]
# set_property PACKAGE_PIN AM27	[get_ports SDA_L2]
# set_property PACKAGE_PIN AD29	[get_ports SCL_L2]
# set_property PACKAGE_PIN AC30	[get_ports {nULED[0]}]
# set_property PACKAGE_PIN AE34	[get_ports SCL_L1]
# set_property PACKAGE_PIN AF34	[get_ports SDA_L1]
# set_property PACKAGE_PIN AG32	[get_ports FPCLKE_P]
# set_property PACKAGE_PIN AH32	[get_ports FPCLKE_N]
# set_property PACKAGE_PIN AJ32	[get_ports FPCLKF_P]
# set_property PACKAGE_PIN AK32	[get_ports FPCLKF_N]
# set_property PACKAGE_PIN AM31	[get_ports {nULED[2]}]
# set_property PACKAGE_PIN AD30	[get_ports {nULED[3]}]
# set_property PACKAGE_PIN AA33	[get_ports D00_MOSIX]
# set_property PACKAGE_PIN AA34	[get_ports D01_MISOX]
# set_property PACKAGE_PIN Y33	[get_ports D02]
# set_property PACKAGE_PIN Y34	[get_ports D03]
# set_property PACKAGE_PIN AD31	[get_ports {nULED[1]}]
# set_property PACKAGE_PIN V30	[get_ports nFCSX]
# set_property PACKAGE_PIN W26	[get_ports FPCLKG_P]
# set_property PACKAGE_PIN W27	[get_ports FPCLKG_N]
# set_property PACKAGE_PIN Y28	[get_ports FPCLKH_P]
# set_property PACKAGE_PIN Y29	[get_ports FPCLKH_N]
# set_property PACKAGE_PIN W34	[get_ports CLK50MHZ]

set_property PACKAGE_PIN AA24	[get_ports FPGA_RX_UART]
set_property PACKAGE_PIN AC24	[get_ports FPGA_TX_UART]

# set_property PACKAGE_PIN V2	[get_ports AMC_TX8_P	]
# set_property PACKAGE_PIN V6	[get_ports AMC_RX8_P	]
# set_property PACKAGE_PIN V1	[get_ports AMC_TX8_N	]
# set_property PACKAGE_PIN V5	[get_ports AMC_RX8_N	]
# set_property PACKAGE_PIN W4	[get_ports AMC_TX9_P	]
# set_property PACKAGE_PIN Y6	[get_ports AMC_RX9_P	]
# set_property PACKAGE_PIN W3	[get_ports AMC_TX9_N	]
# set_property PACKAGE_PIN Y5	[get_ports AMC_RX9_N	]
# set_property PACKAGE_PIN Y2	[get_ports AMC_TX10_P	]
# set_property PACKAGE_PIN AA4	[get_ports AMC_RX10_P	]
# set_property PACKAGE_PIN Y1	[get_ports AMC_TX10_N	]
# set_property PACKAGE_PIN AA3	[get_ports AMC_RX10_N	]
# set_property PACKAGE_PIN AB2	[get_ports AMC_TX11_P	]
# set_property PACKAGE_PIN AB6	[get_ports AMC_RX11_P	]
# set_property PACKAGE_PIN AB1	[get_ports AMC_TX11_N	]
# set_property PACKAGE_PIN AB5	[get_ports AMC_RX11_N	]
set_property PACKAGE_PIN W8	[get_ports CLK100MHZ1_P	]
set_property PACKAGE_PIN W7	[get_ports CLK100MHZ1_N	]

set_property PACKAGE_PIN N4	[get_ports AMC_TX4_P	]
set_property PACKAGE_PIN M6	[get_ports AMC_RX4_P	]
set_property PACKAGE_PIN N3	[get_ports AMC_TX4_N	]
set_property PACKAGE_PIN M5	[get_ports AMC_RX4_N	]
set_property PACKAGE_PIN P2	[get_ports AMC_TX5_P	]
set_property PACKAGE_PIN P6	[get_ports AMC_RX5_P	]
set_property PACKAGE_PIN P1	[get_ports AMC_TX5_N	]
set_property PACKAGE_PIN P5	[get_ports AMC_RX5_N	]
set_property PACKAGE_PIN T2	[get_ports AMC_TX6_P	]
set_property PACKAGE_PIN R4	[get_ports AMC_RX6_P	]
set_property PACKAGE_PIN T1	[get_ports AMC_TX6_N	]
set_property PACKAGE_PIN R3	[get_ports AMC_RX6_N	]
set_property PACKAGE_PIN U4	[get_ports AMC_TX7_P	]
set_property PACKAGE_PIN T6	[get_ports AMC_RX7_P	]
set_property PACKAGE_PIN U3	[get_ports AMC_TX7_N	]
set_property PACKAGE_PIN T5	[get_ports AMC_RX7_N	]
# set_property PACKAGE_PIN R8	[get_ports CLK100MHZ0_P	]
# set_property PACKAGE_PIN R7	[get_ports CLK100MHZ0_N	]
set_property PACKAGE_PIN U7	[get_ports FCLKA_N	]
set_property PACKAGE_PIN U8	[get_ports FCLKA_P	]

set_property PACKAGE_PIN AC30	[get_ports {nULED[0]}	]
set_property PACKAGE_PIN AD31	[get_ports {nULED[1]}	]
set_property PACKAGE_PIN AM31	[get_ports {nULED[2]}	]
set_property PACKAGE_PIN AD30	[get_ports {nULED[3]}	]


# ===================== FMC0 PINS =======================
# set_property PACKAGE_PIN H17	[get_ports nPRSNT_M2C0	]
# set_property PACKAGE_PIN H18	[get_ports CLK_DIR0	]

# set_property PACKAGE_PIN E21	[get_ports FMC0_LA_P0	]
# set_property PACKAGE_PIN E22	[get_ports FMC0_LA_N0	]
# set_property PACKAGE_PIN E19	[get_ports FMC0_LA_P1	]
# set_property PACKAGE_PIN D19	[get_ports FMC0_LA_N1	]
# set_property PACKAGE_PIN M26	[get_ports FMC0_LA_P2	]
# set_property PACKAGE_PIN M27	[get_ports FMC0_LA_N2	]
# set_property PACKAGE_PIN J24	[get_ports FMC0_LA_P3	]
# set_property PACKAGE_PIN J25	[get_ports FMC0_LA_N3	]
# set_property PACKAGE_PIN L24	[get_ports FMC0_LA_P4	]
# set_property PACKAGE_PIN K24	[get_ports FMC0_LA_N4	]
# set_property PACKAGE_PIN K28	[get_ports FMC0_LA_P5	]
# set_property PACKAGE_PIN K29	[get_ports FMC0_LA_N5	]
# set_property PACKAGE_PIN L28	[get_ports FMC0_LA_P6	]
# set_property PACKAGE_PIN L29	[get_ports FMC0_LA_N6	]
# set_property PACKAGE_PIN K26	[get_ports FMC0_LA_P7	]
# set_property PACKAGE_PIN K27	[get_ports FMC0_LA_N7	]
# set_property PACKAGE_PIN H28	[get_ports FMC0_LA_P8	]
# set_property PACKAGE_PIN G28	[get_ports FMC0_LA_N8	]
# set_property PACKAGE_PIN F28	[get_ports FMC0_LA_P9	]
# set_property PACKAGE_PIN E28	[get_ports FMC0_LA_N9	]
# set_property PACKAGE_PIN D26	[get_ports FMC0_LA_P10	]
# set_property PACKAGE_PIN D27	[get_ports FMC0_LA_N10	]
# set_property PACKAGE_PIN H24	[get_ports FMC0_LA_P11	]
# set_property PACKAGE_PIN H25	[get_ports FMC0_LA_N11	]
# set_property PACKAGE_PIN J26	[get_ports FMC0_LA_P12	]
# set_property PACKAGE_PIN J27	[get_ports FMC0_LA_N12	]
# set_property PACKAGE_PIN B26	[get_ports FMC0_LA_P13	]
# set_property PACKAGE_PIN B27	[get_ports FMC0_LA_N13	]
# set_property PACKAGE_PIN B28	[get_ports FMC0_LA_P14	]
# set_property PACKAGE_PIN A28	[get_ports FMC0_LA_N14	]
# set_property PACKAGE_PIN G20	[get_ports FMC0_LA_P15	]
# set_property PACKAGE_PIN G21	[get_ports FMC0_LA_N15	]
# set_property PACKAGE_PIN F23	[get_ports FMC0_LA_P16	]
# set_property PACKAGE_PIN E23	[get_ports FMC0_LA_N16	]
# set_property PACKAGE_PIN E26	[get_ports FMC0_LA_P17	]
# set_property PACKAGE_PIN E27	[get_ports FMC0_LA_N17	]
# set_property PACKAGE_PIN H27	[get_ports FMC0_LA_P18	]
# set_property PACKAGE_PIN G27	[get_ports FMC0_LA_N18	]
# set_property PACKAGE_PIN D24	[get_ports FMC0_LA_P19	]
# set_property PACKAGE_PIN D25	[get_ports FMC0_LA_N19	]
# set_property PACKAGE_PIN F24	[get_ports FMC0_LA_P20	]
# set_property PACKAGE_PIN E24	[get_ports FMC0_LA_N20	]
# set_property PACKAGE_PIN B21	[get_ports FMC0_LA_P21	]
# set_property PACKAGE_PIN A21	[get_ports FMC0_LA_N21	]
# set_property PACKAGE_PIN C23	[get_ports FMC0_LA_P22	]
# set_property PACKAGE_PIN B23	[get_ports FMC0_LA_N22	]
# set_property PACKAGE_PIN G22	[get_ports FMC0_LA_P23	]
# set_property PACKAGE_PIN G23	[get_ports FMC0_LA_N23	]
# set_property PACKAGE_PIN C20	[get_ports FMC0_LA_P24	]
# set_property PACKAGE_PIN B20	[get_ports FMC0_LA_N24	]
# set_property PACKAGE_PIN A19	[get_ports FMC0_LA_P25	]
# set_property PACKAGE_PIN A20	[get_ports FMC0_LA_N25	]
# set_property PACKAGE_PIN B22	[get_ports FMC0_LA_P26	]
# set_property PACKAGE_PIN A23	[get_ports FMC0_LA_N26	]
# set_property PACKAGE_PIN F20	[get_ports FMC0_LA_P27	]
# set_property PACKAGE_PIN F21	[get_ports FMC0_LA_N27	]
# set_property PACKAGE_PIN C17	[get_ports FMC0_LA_P28	]
# set_property PACKAGE_PIN B17	[get_ports FMC0_LA_N28	]
# set_property PACKAGE_PIN B18	[get_ports FMC0_LA_P29	]
# set_property PACKAGE_PIN A18	[get_ports FMC0_LA_N29	]
# set_property PACKAGE_PIN D16	[get_ports FMC0_LA_P30	]
# set_property PACKAGE_PIN D17	[get_ports FMC0_LA_N30	]
# set_property PACKAGE_PIN B16	[get_ports FMC0_LA_P31	]
# set_property PACKAGE_PIN A16	[get_ports FMC0_LA_N31	]
# set_property PACKAGE_PIN F16	[get_ports FMC0_LA_P32	]
# set_property PACKAGE_PIN E16	[get_ports FMC0_LA_N32	]
# set_property PACKAGE_PIN E17	[get_ports FMC0_LA_P33	]
# set_property PACKAGE_PIN E18	[get_ports FMC0_LA_N33	]

# set_property PACKAGE_PIN E31	[get_ports FMC0_HA_P0	]
# set_property PACKAGE_PIN D31	[get_ports FMC0_HA_N0	]
# set_property PACKAGE_PIN G31	[get_ports FMC0_HA_P1	]
# set_property PACKAGE_PIN F31	[get_ports FMC0_HA_N1	]
# set_property PACKAGE_PIN K32	[get_ports FMC0_HA_P2	]
# set_property PACKAGE_PIN J32	[get_ports FMC0_HA_N2	]
# set_property PACKAGE_PIN J34	[get_ports FMC0_HA_P3	]
# set_property PACKAGE_PIN H34	[get_ports FMC0_HA_N3	]
# set_property PACKAGE_PIN H32	[get_ports FMC0_HA_P4	]
# set_property PACKAGE_PIN G32	[get_ports FMC0_HA_N4	]
# set_property PACKAGE_PIN H33	[get_ports FMC0_HA_P5	]
# set_property PACKAGE_PIN G33	[get_ports FMC0_HA_N5	]
# set_property PACKAGE_PIN L33	[get_ports FMC0_HA_P6	]
# set_property PACKAGE_PIN K33	[get_ports FMC0_HA_N6	]
# set_property PACKAGE_PIN L34	[get_ports FMC0_HA_P7	]
# set_property PACKAGE_PIN K34	[get_ports FMC0_HA_N7	]
# set_property PACKAGE_PIN F33	[get_ports FMC0_HA_P8	]
# set_property PACKAGE_PIN E33	[get_ports FMC0_HA_N8	]
# set_property PACKAGE_PIN F34	[get_ports FMC0_HA_P9	]
# set_property PACKAGE_PIN E34	[get_ports FMC0_HA_N09	]
# set_property PACKAGE_PIN H29	[get_ports FMC0_HA_P10	]
# set_property PACKAGE_PIN H30	[get_ports FMC0_HA_N10	]
# set_property PACKAGE_PIN L31	[get_ports FMC0_HA_P11	]
# set_property PACKAGE_PIN K31	[get_ports FMC0_HA_N11	]
# set_property PACKAGE_PIN C32	[get_ports FMC0_HA_P12	]
# set_property PACKAGE_PIN C33	[get_ports FMC0_HA_N12	]
# set_property PACKAGE_PIN D34	[get_ports FMC0_HA_P13	]
# set_property PACKAGE_PIN C34	[get_ports FMC0_HA_N13	]
# set_property PACKAGE_PIN B31	[get_ports FMC0_HA_P14	]
# set_property PACKAGE_PIN B32	[get_ports FMC0_HA_N14	]
# set_property PACKAGE_PIN B30	[get_ports FMC0_HA_P15	]
# set_property PACKAGE_PIN A31	[get_ports FMC0_HA_N15	]
# set_property PACKAGE_PIN B33	[get_ports FMC0_HA_P16	]
# set_property PACKAGE_PIN A33	[get_ports FMC0_HA_N16	]
# set_property PACKAGE_PIN E32	[get_ports FMC0_HA_P17	]
# set_property PACKAGE_PIN D32	[get_ports FMC0_HA_N17	]
# set_property PACKAGE_PIN G30	[get_ports FMC0_HA_P18	]
# set_property PACKAGE_PIN F30	[get_ports FMC0_HA_N18	]
# set_property PACKAGE_PIN F29	[get_ports FMC0_HA_P19	]
# set_property PACKAGE_PIN E29	[get_ports FMC0_HA_N19	]
# set_property PACKAGE_PIN D29	[get_ports FMC0_HA_P20	]
# set_property PACKAGE_PIN D30	[get_ports FMC0_HA_N20	]
# set_property PACKAGE_PIN A29	[get_ports FMC0_HA_P21	]
# set_property PACKAGE_PIN A30	[get_ports FMC0_HA_N21	]
# set_property PACKAGE_PIN C24	[get_ports FMC0_HA_P22	]
# set_property PACKAGE_PIN C25	[get_ports FMC0_HA_N22	]
# set_property PACKAGE_PIN A24	[get_ports FMC0_HA_P23	]
# set_property PACKAGE_PIN A25	[get_ports FMC0_HA_N23	]

# set_property PACKAGE_PIN T28	[get_ports FMC0_HB_P0	]
# set_property PACKAGE_PIN T29	[get_ports FMC0_HB_N0	]
# set_property PACKAGE_PIN U25	[get_ports FMC0_HB_P1	]
# set_property PACKAGE_PIN U26	[get_ports FMC0_HB_N1	]
# set_property PACKAGE_PIN R26	[get_ports FMC0_HB_P2	]
# set_property PACKAGE_PIN R27	[get_ports FMC0_HB_N2	]
# set_property PACKAGE_PIN P25	[get_ports FMC0_HB_P3	]
# set_property PACKAGE_PIN P26	[get_ports FMC0_HB_N3	]
# set_property PACKAGE_PIN U27	[get_ports FMC0_HB_P4	]
# set_property PACKAGE_PIN U28	[get_ports FMC0_HB_N4	]
# set_property PACKAGE_PIN T25	[get_ports FMC0_HB_P5	]
# set_property PACKAGE_PIN T26	[get_ports FMC0_HB_N5	]
# set_property PACKAGE_PIN R31	[get_ports FMC0_HB_P6	]
# set_property PACKAGE_PIN P31	[get_ports FMC0_HB_N6	]
# set_property PACKAGE_PIN U32	[get_ports FMC0_HB_P7	]
# set_property PACKAGE_PIN U33	[get_ports FMC0_HB_N7	]
# set_property PACKAGE_PIN R32	[get_ports FMC0_HB_P8	]
# set_property PACKAGE_PIN P32	[get_ports FMC0_HB_N8	]
# set_property PACKAGE_PIN R33	[get_ports FMC0_HB_P9	]
# set_property PACKAGE_PIN R34	[get_ports FMC0_HB_N9	]
# set_property PACKAGE_PIN T30	[get_ports FMC0_HB_P10	]
# set_property PACKAGE_PIN T31	[get_ports FMC0_HB_N10	]
# set_property PACKAGE_PIN T33	[get_ports FMC0_HB_P11	]
# set_property PACKAGE_PIN T34	[get_ports FMC0_HB_N11	]
# set_property PACKAGE_PIN N32	[get_ports FMC0_HB_P12	]
# set_property PACKAGE_PIN M32	[get_ports FMC0_HB_N12	]
# set_property PACKAGE_PIN N33	[get_ports FMC0_HB_P13	]
# set_property PACKAGE_PIN M33	[get_ports FMC0_HB_N13	]
# set_property PACKAGE_PIN P30	[get_ports FMC0_HB_P14	]
# set_property PACKAGE_PIN N30	[get_ports FMC0_HB_N14	]
# set_property PACKAGE_PIN P34	[get_ports FMC0_HB_P15	]
# set_property PACKAGE_PIN N34	[get_ports FMC0_HB_N15	]
# set_property PACKAGE_PIN P29	[get_ports FMC0_HB_P16	]
# set_property PACKAGE_PIN N29	[get_ports FMC0_HB_N16	]
# set_property PACKAGE_PIN R28	[get_ports FMC0_HB_P17	]
# set_property PACKAGE_PIN R29	[get_ports FMC0_HB_N17	]
# set_property PACKAGE_PIN N28	[get_ports FMC0_HB_P18	]
# set_property PACKAGE_PIN M28	[get_ports FMC0_HB_N18	]
# set_property PACKAGE_PIN M30	[get_ports FMC0_HB_P19	]
# set_property PACKAGE_PIN M31	[get_ports FMC0_HB_N19	]
# set_property PACKAGE_PIN N24	[get_ports FMC0_HB_P20	]
# set_property PACKAGE_PIN N25	[get_ports FMC0_HB_N20	]
# set_property PACKAGE_PIN P27	[get_ports FMC0_HB_P21	]
# set_property PACKAGE_PIN N27	[get_ports FMC0_HB_N21	]


#set_property PACKAGE_PIN B6	[get_ports FMC0_TX3_P	]
#set_property PACKAGE_PIN B5	[get_ports FMC0_TX3_N	]
#set_property PACKAGE_PIN A4	[get_ports FMC0_TX2_P	]
#set_property PACKAGE_PIN A3	[get_ports RMC0_TX2_N	]
#set_property PACKAGE_PIN B2	[get_ports FMC0_TX1_P	]
#set_property PACKAGE_PIN B1	[get_ports FMC0_TX1_N	]
#set_property PACKAGE_PIN D2	[get_ports FMC0_TX0_P	]
#set_property PACKAGE_PIN D1	[get_ports FMC0_TX0_N	]
	
# set_property PACKAGE_PIN C4	[get_ports FMC0_RX3_P	]
# set_property PACKAGE_PIN C3	[get_ports FMC0_RX3_N	]
# set_property PACKAGE_PIN D6	[get_ports FMC0_RX2_P	]
# set_property PACKAGE_PIN D5	[get_ports FMC0_RX2_N	]
# set_property PACKAGE_PIN E4	[get_ports FMC0_RX1_P	]
# set_property PACKAGE_PIN E3	[get_ports FMC0_RX1_N	]
# set_property PACKAGE_PIN G4	[get_ports FMC0_RX0_P	]
# set_property PACKAGE_PIN G3	[get_ports FMC0_RX0_N	]
# set_property PACKAGE_PIN F6	[get_ports FMC0_GBTCLK0_P]
# set_property PACKAGE_PIN F5	[get_ports FMC0_GBTCLK0_N]
# set_property PACKAGE_PIN G7	[get_ports FMC0_GBTCLK1_N]
# set_property PACKAGE_PIN G8	[get_ports FMC0_GBTCLK1_P]

#set_property PACKAGE_PIN A12	[get_ports FMC0_TX7_P	]
#set_property PACKAGE_PIN A11	[get_ports FMC0_TX7_N	]
#set_property PACKAGE_PIN B10	[get_ports FMC0_TX6_P	]
#set_property PACKAGE_PIN B9	[get_ports FMC0_TX6_N	]
#set_property PACKAGE_PIN A8	[get_ports FMC0_TX5_P	]
#set_property PACKAGE_PIN A7	[get_ports FMC0_TX5_N	]
#set_property PACKAGE_PIN C8	[get_ports FMC0_TX4_P	]
#set_property PACKAGE_PIN C7	[get_ports FMC0_TX4_N	]
	
# set_property PACKAGE_PIN C12	[get_ports FMC0_RX7_P	]
# set_property PACKAGE_PIN C11	[get_ports FMC0_RX7_N	]
# set_property PACKAGE_PIN D10	[get_ports FMC0_RX6_P	]
# set_property PACKAGE_PIN D9	[get_ports FMC0_RX6_N	]
# set_property PACKAGE_PIN E12	[get_ports FMC0_RX5_P	]
# set_property PACKAGE_PIN E11	[get_ports FMC0_RX5_N	]
# set_property PACKAGE_PIN F10	[get_ports FMC0_RX4_P	]
# set_property PACKAGE_PIN F9	[get_ports FMC0_RX4_N	]
# set_property PACKAGE_PIN E8	[get_ports CLK156_25MHZ3_P]
# set_property PACKAGE_PIN E7	[get_ports CLK156_25MHZ3_N]
# set_property PACKAGE_PIN H9	[get_ports CLK125MHZ3_N	]
# set_property PACKAGE_PIN H10	[get_ports CLK125MHZ3_P	]


#set_property PACKAGE_PIN F2	[get_ports FMC0_TX9_P	]
#set_property PACKAGE_PIN F1	[get_ports FMC0_TX9_N	]
#set_property PACKAGE_PIN H2	[get_ports FMC0_TX8_P	]
#set_property PACKAGE_PIN H1	[get_ports FMC0_TX8_N	]
#set_property PACKAGE_PIN H6	[get_ports FMC0_RX9_P	]
#set_property PACKAGE_PIN H5	[get_ports FMC0_RX9_N	]
#set_property PACKAGE_PIN J4	[get_ports FMC0_RX8_P	]
#set_property PACKAGE_PIN J3	[get_ports FMC0_RX8_N	]
# set_property PACKAGE_PIN J8	[get_ports CLK156_25MHZ2_P]
# set_property PACKAGE_PIN J7	[get_ports CLK156_25MHZ2_N]
# set_property PACKAGE_PIN L7	[get_ports CLK125MHZ2_N	]
# set_property PACKAGE_PIN L8	[get_ports CLK125MHZ2_P	]
#set_property PACKAGE_PIN K2	[get_ports AMC_TX1_P]
#set_property PACKAGE_PIN K6	[get_ports AMC_RX1_P]
#set_property PACKAGE_PIN K1	[get_ports AMC_TX1_N]
#set_property PACKAGE_PIN K5	[get_ports AMC_RX1_N]
#set_property PACKAGE_PIN M2	[get_ports AMC_TX0_P]
#set_property PACKAGE_PIN L4	[get_ports AMC_RX0_P]
#set_property PACKAGE_PIN M1	[get_ports AMC_TX0_N]
#set_property PACKAGE_PIN L3	[get_ports AMC_RX0_N]

# ===================== FMC1 PINS =======================
# set_property PACKAGE_PIN G17	[get_ports nPRSNT_M2C1	]
# set_property PACKAGE_PIN G18	[get_ports CLK_DIR1	]

# set_property PACKAGE_PIN Y26	[get_ports FMC1_LA_P0	]
# set_property PACKAGE_PIN Y27	[get_ports FMC1_LA_N0	]
set_property PACKAGE_PIN AA28	[get_ports FMC1_LA_P1	]
set_property PACKAGE_PIN AA29	[get_ports FMC1_LA_N1	]
set_property PACKAGE_PIN AL29	[get_ports FMC1_LA_P2	]
set_property PACKAGE_PIN AM30	[get_ports FMC1_LA_N2	]
set_property PACKAGE_PIN AP29	[get_ports FMC1_LA_P3	]
set_property PACKAGE_PIN AP30	[get_ports FMC1_LA_N3	]
set_property PACKAGE_PIN AN29	[get_ports FMC1_LA_P4	]
set_property PACKAGE_PIN AN30	[get_ports FMC1_LA_N4	]
set_property PACKAGE_PIN V29	[get_ports FMC1_LA_P5	]
set_property PACKAGE_PIN W29	[get_ports FMC1_LA_N5	]
set_property PACKAGE_PIN V27	[get_ports FMC1_LA_P6	]
set_property PACKAGE_PIN V28	[get_ports FMC1_LA_N6	]
set_property PACKAGE_PIN AN32	[get_ports FMC1_LA_P7	]
set_property PACKAGE_PIN AP33	[get_ports FMC1_LA_N7	]
set_property PACKAGE_PIN AP31	[get_ports FMC1_LA_P8	]
# set_property PACKAGE_PIN AP32	[get_ports FMC1_LA_N8	]
set_property PACKAGE_PIN Y31	[get_ports FMC1_LA_P9	]
set_property PACKAGE_PIN Y32	[get_ports FMC1_LA_N9	]
set_property PACKAGE_PIN AB32	[get_ports FMC1_LA_P10	]
set_property PACKAGE_PIN AB33	[get_ports FMC1_LA_N10	]
set_property PACKAGE_PIN AH30	[get_ports FMC1_LA_P11	]
set_property PACKAGE_PIN AJ30	[get_ports FMC1_LA_N11	]
set_property PACKAGE_PIN AM33	[get_ports FMC1_LA_P12	]
set_property PACKAGE_PIN AN34	[get_ports FMC1_LA_N12	]
set_property PACKAGE_PIN AA25	[get_ports FMC1_LA_P13	]
set_property PACKAGE_PIN AB25	[get_ports FMC1_LA_N13	]
set_property PACKAGE_PIN AC27	[get_ports FMC1_LA_P14	]
set_property PACKAGE_PIN AD27	[get_ports FMC1_LA_N14	]
set_property PACKAGE_PIN AH34	[get_ports FMC1_LA_P15	]
set_property PACKAGE_PIN AJ34	[get_ports FMC1_LA_N15	]
set_property PACKAGE_PIN AK33	[get_ports FMC1_LA_P16	]
set_property PACKAGE_PIN AL33	[get_ports FMC1_LA_N16	]
# set_property PACKAGE_PIN AF31	[get_ports FMC1_LA_P17	]
# set_property PACKAGE_PIN AG31	[get_ports FMC1_LA_N17	]
set_property PACKAGE_PIN AJ31	[get_ports FMC1_LA_P18	]
set_property PACKAGE_PIN AK31	[get_ports FMC1_LA_N18	]
set_property PACKAGE_PIN AF30	[get_ports FMC1_LA_P19	]
set_property PACKAGE_PIN AG30	[get_ports FMC1_LA_N19	]
set_property PACKAGE_PIN W24	[get_ports FMC1_LA_P20	]
set_property PACKAGE_PIN Y24	[get_ports FMC1_LA_N20	]
set_property PACKAGE_PIN AE31	[get_ports FMC1_LA_P21	]
set_property PACKAGE_PIN AE32	[get_ports FMC1_LA_N21	]
# set_property PACKAGE_PIN AE33	[get_ports FMC1_LA_P22	]
# set_property PACKAGE_PIN AF33	[get_ports FMC1_LA_N22	]
set_property PACKAGE_PIN AG33	[get_ports FMC1_LA_P23	]
set_property PACKAGE_PIN AH33	[get_ports FMC1_LA_N23	]
set_property PACKAGE_PIN AB30	[get_ports FMC1_LA_P24	]
set_property PACKAGE_PIN AB31	[get_ports FMC1_LA_N24	]
set_property PACKAGE_PIN AC28	[get_ports FMC1_LA_P25	]
set_property PACKAGE_PIN AC29	[get_ports FMC1_LA_N25	]
# set_property PACKAGE_PIN AK34	[get_ports FMC1_LA_P26	]
# set_property PACKAGE_PIN AL34	[get_ports FMC1_LA_N26	]
# set_property PACKAGE_PIN AL30	[get_ports FMC1_LA_P27	]
# set_property PACKAGE_PIN AL31	[get_ports FMC1_LA_N27	]
# set_property PACKAGE_PIN AC25	[get_ports FMC1_LA_P28	]
# set_property PACKAGE_PIN AD26	[get_ports FMC1_LA_N28	]
# set_property PACKAGE_PIN V25	[get_ports FMC1_LA_P29	]
# set_property PACKAGE_PIN W25	[get_ports FMC1_LA_N29	]
# set_property PACKAGE_PIN W31	[get_ports FMC1_LA_P30	]
# set_property PACKAGE_PIN W32	[get_ports FMC1_LA_N30	]
# set_property PACKAGE_PIN V32	[get_ports FMC1_LA_P31	]
# set_property PACKAGE_PIN V33	[get_ports FMC1_LA_N31	]
# set_property PACKAGE_PIN AB27	[get_ports FMC1_LA_P32	]
# set_property PACKAGE_PIN AB28	[get_ports FMC1_LA_N32	]
# set_property PACKAGE_PIN AA30	[get_ports FMC1_LA_P33	]
# set_property PACKAGE_PIN AA31	[get_ports FMC1_LA_N33	]

# set_property PACKAGE_PIN AL25	[get_ports FMC1_HA_P0	]
# set_property PACKAGE_PIN AL26	[get_ports FMC1_HA_N0	]
# set_property PACKAGE_PIN AH27	[get_ports FMC1_HA_P1	]
# set_property PACKAGE_PIN AH28	[get_ports FMC1_HA_N1	]
# set_property PACKAGE_PIN AN27	[get_ports FMC1_HA_P2	]
# set_property PACKAGE_PIN AN28	[get_ports FMC1_HA_N2	]
# set_property PACKAGE_PIN AK24	[get_ports FMC1_HA_P3	]
# set_property PACKAGE_PIN AL24	[get_ports FMC1_HA_N3	]
# set_property PACKAGE_PIN AP26	[get_ports FMC1_HA_P4	]
# set_property PACKAGE_PIN AP27	[get_ports FMC1_HA_N4	]
# set_property PACKAGE_PIN AN25	[get_ports FMC1_HA_P5	]
# set_property PACKAGE_PIN AP25	[get_ports FMC1_HA_N5	]
# set_property PACKAGE_PIN AK28	[get_ports FMC1_HA_P6	]
# set_property PACKAGE_PIN AL28	[get_ports FMC1_HA_N6	]
# set_property PACKAGE_PIN AN24	[get_ports FMC1_HA_P7	]
# set_property PACKAGE_PIN AP24	[get_ports FMC1_HA_N7	]
# set_property PACKAGE_PIN AH24	[get_ports FMC1_HA_P8	]
# set_property PACKAGE_PIN AJ24	[get_ports FMC1_HA_N8	]
# set_property PACKAGE_PIN AM25	[get_ports FMC1_HA_P9	]
# set_property PACKAGE_PIN AM26	[get_ports FMC1_HA_N9	]
# set_property PACKAGE_PIN AE26	[get_ports FMC1_HA_P10	]
# set_property PACKAGE_PIN AF26	[get_ports FMC1_HA_N10	]
# set_property PACKAGE_PIN AM23	[get_ports FMC1_HA_P11	]
# set_property PACKAGE_PIN AN23	[get_ports FMC1_HA_N11	]
# set_property PACKAGE_PIN AH25	[get_ports FMC1_HA_P12	]
# set_property PACKAGE_PIN AJ25	[get_ports FMC1_HA_N12	]
# set_property PACKAGE_PIN AJ29	[get_ports FMC1_HA_P13	]
# set_property PACKAGE_PIN AK29	[get_ports FMC1_HA_N13	]
# set_property PACKAGE_PIN AG28	[get_ports FMC1_HA_P14	]
# set_property PACKAGE_PIN AH29	[get_ports FMC1_HA_N14	]
# set_property PACKAGE_PIN AF28	[get_ports FMC1_HA_P15	]
# set_property PACKAGE_PIN AF29	[get_ports FMC1_HA_N15	]
# set_property PACKAGE_PIN AG26	[get_ports FMC1_HA_P16	]
# set_property PACKAGE_PIN AG27	[get_ports FMC1_HA_N16	]
# set_property PACKAGE_PIN AK26	[get_ports FMC1_HA_P17	]
# set_property PACKAGE_PIN AK27	[get_ports FMC1_HA_N17	]
# set_property PACKAGE_PIN AJ26	[get_ports FMC1_HA_P18	]
# set_property PACKAGE_PIN AJ27	[get_ports FMC1_HA_N18	]
# set_property PACKAGE_PIN AC34	[get_ports FMC1_HA_P19	]
# set_property PACKAGE_PIN AD34	[get_ports FMC1_HA_N19	]
# set_property PACKAGE_PIN AE27	[get_ports FMC1_HA_P20	]
# set_property PACKAGE_PIN AE28	[get_ports FMC1_HA_N20	]
# set_property PACKAGE_PIN AC32	[get_ports FMC1_HA_P21	]
# set_property PACKAGE_PIN AC33	[get_ports FMC1_HA_N21	]
# set_property PACKAGE_PIN AF25	[get_ports FMC1_HA_P22	]
# set_property PACKAGE_PIN AG25	[get_ports FMC1_HA_N22	]
# set_property PACKAGE_PIN AE24	[get_ports FMC1_HA_P23	]
# set_property PACKAGE_PIN AF24	[get_ports FMC1_HA_N23	]

# set_property PACKAGE_PIN AL20	[get_ports FMC1_HB_P0	]
# set_property PACKAGE_PIN AM20	[get_ports FMC1_HB_N0	]
# set_property PACKAGE_PIN AP16	[get_ports FMC1_HB_P1	]
# set_property PACKAGE_PIN AP17	[get_ports FMC1_HB_N1	]
# set_property PACKAGE_PIN AL16	[get_ports FMC1_HB_P2	]
# set_property PACKAGE_PIN AM16	[get_ports FMC1_HB_N2	]
# set_property PACKAGE_PIN AK16	[get_ports FMC1_HB_P3	]
# set_property PACKAGE_PIN AK17	[get_ports FMC1_HB_N3	]
# set_property PACKAGE_PIN AN19	[get_ports FMC1_HB_P4	]
# set_property PACKAGE_PIN AP19	[get_ports FMC1_HB_N4	]
# set_property PACKAGE_PIN AN17	[get_ports FMC1_HB_P5	]
# set_property PACKAGE_PIN AN18	[get_ports FMC1_HB_N5	]
# set_property PACKAGE_PIN AK18	[get_ports FMC1_HB_P6	]
# set_property PACKAGE_PIN AK19	[get_ports FMC1_HB_N6	]
# set_property PACKAGE_PIN AN20	[get_ports FMC1_HB_P7	]
# set_property PACKAGE_PIN AP20	[get_ports FMC1_HB_N7	]
# set_property PACKAGE_PIN AM22	[get_ports FMC1_HB_P8	]
# set_property PACKAGE_PIN AN22	[get_ports FMC1_HB_N8	]
# set_property PACKAGE_PIN AP21	[get_ports FMC1_HB_P9	]
# set_property PACKAGE_PIN AP22	[get_ports FMC1_HB_N9	]
# set_property PACKAGE_PIN AH17	[get_ports FMC1_HB_P10	]
# set_property PACKAGE_PIN AH18	[get_ports FMC1_HB_N10	]
# set_property PACKAGE_PIN AG16	[get_ports FMC1_HB_P11	]
# set_property PACKAGE_PIN AG17	[get_ports FMC1_HB_N11	]
# set_property PACKAGE_PIN AG22	[get_ports FMC1_HB_P12	]
# set_property PACKAGE_PIN AH22	[get_ports FMC1_HB_N12	]
# set_property PACKAGE_PIN AK23	[get_ports FMC1_HB_P13	]
# set_property PACKAGE_PIN AL23	[get_ports FMC1_HB_N13	]
# set_property PACKAGE_PIN AH19	[get_ports FMC1_HB_P14	]
# set_property PACKAGE_PIN AJ19	[get_ports FMC1_HB_N14	]
# set_property PACKAGE_PIN AJ16	[get_ports FMC1_HB_P15	]
# set_property PACKAGE_PIN AJ17	[get_ports FMC1_HB_N15	]
# set_property PACKAGE_PIN AH20	[get_ports FMC1_HB_P16	]
# set_property PACKAGE_PIN AJ20	[get_ports FMC1_HB_N16	]
# set_property PACKAGE_PIN AL18	[get_ports FMC1_HB_P17	]
# set_property PACKAGE_PIN AL19	[get_ports FMC1_HB_N17	]
# set_property PACKAGE_PIN AG20	[get_ports FMC1_HB_P18	]
# set_property PACKAGE_PIN AG21	[get_ports FMC1_HB_N18	]
# set_property PACKAGE_PIN AM17	[get_ports FMC1_HB_P19	]
# set_property PACKAGE_PIN AM18	[get_ports FMC1_HB_N19	]
# set_property PACKAGE_PIN AJ21	[get_ports FMC1_HB_P20	]
# set_property PACKAGE_PIN AK21	[get_ports FMC1_HB_N20	]
# set_property PACKAGE_PIN AG23	[get_ports FMC1_HB_P21	]
# set_property PACKAGE_PIN AH23	[get_ports FMC1_HB_N21	]

#set_property PACKAGE_PIN AM2	[get_ports FMC1_TX3_P	]
#set_property PACKAGE_PIN AM1	[get_ports FMC1_TX3_N	]
#set_property PACKAGE_PIN AP2	[get_ports FMC1_TX2_P	]
#set_property PACKAGE_PIN AP1	[get_ports FMC1_TX2_N	]
#set_property PACKAGE_PIN AN4	[get_ports FMC1_TX1_P	]
#set_property PACKAGE_PIN AN3	[get_ports FMC1_TX1_N	]
#set_property PACKAGE_PIN AP6	[get_ports FMC1_TX0_P	]
#set_property PACKAGE_PIN AP5	[get_ports RMC1_TX0_N	]

set_property PACKAGE_PIN AJ4	[get_ports FMC1_RX3_P	]
set_property PACKAGE_PIN AJ3	[get_ports FMC1_RX3_N	]
set_property PACKAGE_PIN AK6	[get_ports FMC1_RX2_P	]
set_property PACKAGE_PIN AK5	[get_ports FMC1_RX2_N	]
set_property PACKAGE_PIN AL4	[get_ports FMC1_RX1_P	]
set_property PACKAGE_PIN AL3	[get_ports FMC1_RX1_N	]
set_property PACKAGE_PIN AM6	[get_ports FMC1_RX0_P	]
set_property PACKAGE_PIN AM5	[get_ports FMC1_RX0_N	]
set_property PACKAGE_PIN AG8	[get_ports FMC1_GBTCLK0_P]
set_property PACKAGE_PIN AG7	[get_ports FMC1_GBTCLK0_N]
# set_property PACKAGE_PIN AH5	[get_ports FMC1_GBTCLK1_N]
# set_property PACKAGE_PIN AH6	[get_ports FMC1_GBTCLK1_P]


#set_property PACKAGE_PIN AL8	[get_ports FMC1_TX7_P	]
#set_property PACKAGE_PIN AL7	[get_ports FMC1_TX7_N	]
#set_property PACKAGE_PIN AN8	[get_ports FMC1_TX6_P	]
#set_property PACKAGE_PIN AN7	[get_ports FMC1_TX6_N	]
#set_property PACKAGE_PIN AP10	[get_ports FMC1_TX5_P	]
#set_property PACKAGE_PIN AP9	[get_ports FMC1_TX5_N	]
#set_property PACKAGE_PIN AN12	[get_ports FMC1_TX4_P	]
#set_property PACKAGE_PIN AN11	[get_ports FMC1_TX4_N	]

set_property PACKAGE_PIN AK10	[get_ports FMC1_RX7_P	]
set_property PACKAGE_PIN AK9	[get_ports FMC1_RX7_N	]
set_property PACKAGE_PIN AJ12	[get_ports FMC1_RX6_P	]
set_property PACKAGE_PIN AJ11	[get_ports FMC1_RX6_N	]
set_property PACKAGE_PIN AL12	[get_ports FMC1_RX5_P	]
set_property PACKAGE_PIN AL11	[get_ports FMC1_RX5_N	]
set_property PACKAGE_PIN AM10	[get_ports FMC1_RX4_P	]
set_property PACKAGE_PIN AM9	[get_ports FMC1_RX4_N	]
# set_property PACKAGE_PIN AH10	[get_ports CLK156_25MHZ0_P]
# set_property PACKAGE_PIN AH9	[get_ports CLK156_25MHZ0_N]
# set_property PACKAGE_PIN AJ7	[get_ports CLK125MHZ0_N	]
# set_property PACKAGE_PIN AJ8	[get_ports CLK125MHZ0_P	]

#set_property PACKAGE_PIN AD2	[get_ports AMC_TX3_P	]
#set_property PACKAGE_PIN AC4	[get_ports AMC_RX3_P	]
#set_property PACKAGE_PIN AD1	[get_ports AMC_TX3_N	]
#set_property PACKAGE_PIN AC3	[get_ports AMC_RX3_N	]
#set_property PACKAGE_PIN AF2	[get_ports AMC_TX2_P	]
#set_property PACKAGE_PIN AE4	[get_ports AMC_RX2_P	]
#set_property PACKAGE_PIN AF1	[get_ports AMC_TX2_N	]
#set_property PACKAGE_PIN AE3	[get_ports AMC_RX2_N	]

#set_property PACKAGE_PIN AH2	[get_ports FMC1_TX9_P	]
#set_property PACKAGE_PIN AH1	[get_ports FMC1_TX9_N	]
#set_property PACKAGE_PIN AK2	[get_ports FMC1_TX8_P	]
#set_property PACKAGE_PIN AK1	[get_ports FMC1_TX8_N	]
#set_property PACKAGE_PIN AF6	[get_ports FMC1_RX9_P	]
#set_property PACKAGE_PIN AF5	[get_ports FMC1_RX9_N	]
#set_property PACKAGE_PIN AG4	[get_ports FMC1_RX8_P	]
#set_property PACKAGE_PIN AG3	[get_ports FMC1_RX8_N	]
# set_property PACKAGE_PIN AC8	[get_ports CLK156_25MHZ1_P]
# set_property PACKAGE_PIN AC7	[get_ports CLK156_25MHZ1_N]
# set_property PACKAGE_PIN AD5	[get_ports CLK125MHZ1_N	]
# set_property PACKAGE_PIN AD6	[get_ports CLK125MHZ1_P	]


# ===================== IOSTANDARD =======================
set_property IOSTANDARD LVCMOS25	[get_ports FPGA_RX_UART]
set_property IOSTANDARD LVCMOS25	[get_ports FPGA_TX_UART]

set_property IOSTANDARD LVCMOS25	[get_ports {nULED[0]}	]
set_property IOSTANDARD LVCMOS25	[get_ports {nULED[1]}	]
set_property IOSTANDARD LVCMOS25	[get_ports {nULED[2]}	]
set_property IOSTANDARD LVCMOS25	[get_ports {nULED[3]}	]

# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P0	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N0	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P1	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N1	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P2	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N2	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P3	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N3	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P4	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N4	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P5	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N5	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P6	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N6	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P7	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N7	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P8	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N8	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P9	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N9	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P10	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N10	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P11	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N11	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P12	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N12	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P13	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N13	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P14	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N14	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P15	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N15	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P16	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N16	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P17	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N17	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P18	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N18	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P19	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N19	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P20	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N20	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P21	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N21	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P22	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N22	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P23	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N23	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P24	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N24	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P25	]
set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N25	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P26	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N26	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P27	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N27	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P28	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N28	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P29	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N29	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P30	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N30	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P31	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N31	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P32	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N32	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_P33	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_LA_N33	]

# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P0	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N0	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P1	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N1	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P2	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N2	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P3	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N3	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P4	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N4	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P5	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N5	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P6	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N6	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P7	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N7	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P8	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N8	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P9	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N09	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P10	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N10	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P11	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N11	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P12	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N12	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P13	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N13	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P14	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N14	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P15	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N15	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P16	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N16	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P17	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N17	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P18	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N18	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P19	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N19	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P20	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N20	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P21	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N21	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P22	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N22	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_P23	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HA_N23	]

# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P0	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N0	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P1	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N1	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P2	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N2	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P3	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N3	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P4	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N4	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P5	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N5	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P6	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N6	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P7	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N7	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P8	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N8	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P9	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N9	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P10	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N10	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P11	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N11	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P12	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N12	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P13	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N13	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P14	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N14	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P15	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N15	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P16	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N16	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P17	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N17	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P18	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N18	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P19	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N19	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P20	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N20	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_P21	]
# set_property IOSTANDARD LVCMOS25	[get_ports FMC1_HB_N21	]

# ======== Bitstream settings ========
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

