# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k420tffg1156-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.cache/wt [current_project]
set_property parent.project_path /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_ip -quiet /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property is_locked true [get_files /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top fifo_generator_0 -part xc7k420tffg1156-2 -mode out_of_context

rename_ref -prefix_all fifo_generator_0_

write_checkpoint -force -noxdef fifo_generator_0.dcp

catch { report_utilization -file fifo_generator_0_utilization_synth.rpt -pb fifo_generator_0_utilization_synth.pb }

if { [catch {
  write_verilog -force -mode synth_stub /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

add_files /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0_stub.v -of_objects [get_files /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci]

add_files /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0_stub.vhdl -of_objects [get_files /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci]

add_files /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0_sim_netlist.v -of_objects [get_files /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci]

add_files /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0_sim_netlist.vhdl -of_objects [get_files /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci]

add_files /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp -of_objects [get_files /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci]

if {[file isdir /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.ip_user_files/ip/fifo_generator_0]} {
  catch { 
    file copy -force /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0_sim_netlist.v /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.ip_user_files/ip/fifo_generator_0
  }
}

if {[file isdir /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.ip_user_files/ip/fifo_generator_0]} {
  catch { 
    file copy -force /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0_sim_netlist.vhdl /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.ip_user_files/ip/fifo_generator_0
  }
}

if {[file isdir /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.ip_user_files/ip/fifo_generator_0]} {
  catch { 
    file copy -force /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0_stub.v /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.ip_user_files/ip/fifo_generator_0
  }
}

if {[file isdir /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.ip_user_files/ip/fifo_generator_0]} {
  catch { 
    file copy -force /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.runs/fifo_generator_0_synth_1/fifo_generator_0_stub.vhdl /root/Documents/mu2e/mu2e_UEM_firmware/mu2e_UEM_firmware.ip_user_files/ip/fifo_generator_0
  }
}
