# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k420tffg1156-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/amc502_fmc228_f0.cache/wt [current_project]
set_property parent.project_path /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/amc502_fmc228_f0.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/common/ip_repo/fsl_elbc_axi4lite_bridge [current_project]
add_files /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/sdk/fmc228_tool/Debug/fmc228_tool.elf
set_property SCOPED_TO_REF design_1 [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/sdk/fmc228_tool/Debug/fmc228_tool.elf]
set_property SCOPED_TO_CELLS microblaze_0 [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/sdk/fmc228_tool/Debug/fmc228_tool.elf]
add_files -quiet /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/ip/axi_crossbar_0/axi_crossbar_0.dcp
set_property used_in_implementation false [get_files /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/ip/axi_crossbar_0/axi_crossbar_0.dcp]
add_files -quiet /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/ip/fifo_generator_0/fifo_generator_0.dcp
set_property used_in_implementation false [get_files /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/ip/fifo_generator_0/fifo_generator_0.dcp]
add_files -quiet /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/ip/ila_0/ila_0.dcp
set_property used_in_implementation false [get_files /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/ip/ila_0/ila_0.dcp]
add_files -quiet /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/ip/jesd204_0/jesd204_0.dcp
set_property used_in_implementation false [get_files /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/ip/jesd204_0/jesd204_0.dcp]
add_files -quiet /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/ip/jesd204_0_phy/jesd204_0_phy.dcp
set_property used_in_implementation false [get_files /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/ip/jesd204_0_phy/jesd204_0_phy.dcp]
add_files /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_pcie_0_0/design_1_axi_pcie_0_0/source/axi_pcie_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_pcie_0_0/synth/design_1_axi_pcie_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/jesd204_0_support.v
read_vhdl -library xil_defaultlib {
  /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/amc502_fmc228_f0.vhd
  /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/common/axi_gpio_32.vhd
  /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/common/axi_spi_sdio.vhd
  /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/common/vt_single_sync.vhd
  /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/common/axi_lite_rd_fifo.vhd
  /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/common/fmc228.vhd
  /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/common/amc_common_reg.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top amc502_fmc228_fpga_f0 -part xc7k420tffg1156-2


write_checkpoint -force -noxdef amc502_fmc228_fpga_f0.dcp

catch { report_utilization -file amc502_fmc228_fpga_f0_utilization_synth.rpt -pb amc502_fmc228_fpga_f0_utilization_synth.pb }
