# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/amc502_pins_f0.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/amc502_impl_f0.xdc

# Block Designs: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_pcie_0_0/design_1_axi_pcie_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_pcie_0_0 || ORIG_REF_NAME==design_1_axi_pcie_0_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_0 || ORIG_REF_NAME==design_1_ilmb_v10_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_0 || ORIG_REF_NAME==design_1_lmb_bram_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0}]

# IP: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0}]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_pcie_0_0/design_1_axi_pcie_0_0/source/axi_pcie_X0Y0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_pcie_0_0 || ORIG_REF_NAME==design_1_axi_pcie_0_0}] {/U0 }]/U0 ]]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_pcie_0_0/synth/design_1_axi_pcie_0_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_rst_clk_wiz_1_100M_0/design_1_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_0 || ORIG_REF_NAME==design_1_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0}] {/inst }]/inst ]]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1}] {/inst }]/inst ]]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0}] {/inst }]/inst ]]

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: /disk2/data/tmnguyen/mu2e_monitor_firmware_original/Vadatech_example/vada_exaple/sources/amc502/bd/design_1/design_1_ooc.xdc
